name: "Infra Pipeline"

on:
  push:
    branches:
      - main
      - 'releases/**'
permissions:
  id-token: write
  contents: read   
  
jobs:
  Terraform_init_plan_apply_Job:
    runs-on: [self-hosted, Raghav]
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
          
      - name: Terraform fmt
        id: fmt
        working-directory: D:\actions-runner\_work\Terraform-Variable\Terraform-Variable
        run: terraform fmt -check
        continue-on-error: true
  
      - name: Terraform Init
        id: init
        working-directory: D:\actions-runner\_work\Terraform-Variable\Terraform-Variable
        run: terraform init 
  
      - name: Terraform Validate
        id: validate
        working-directory: D:\actions-runner\_work\Terraform-Variable\Terraform-Variable
        run: terraform validate 
  
      - name: Terraform Plan
        id: plan
        working-directory: D:\actions-runner\_work\Terraform-Variable\Terraform-Variable
        run: terraform plan -no-color 
        continue-on-error: true

      - name: Terraform Apply
        id: apply
        working-directory: D:\actions-runner\_work\Terraform-Variable\Terraform-Variable
        run: terraform apply 
  
